const spaceships = [
	{
		id: 1000,
		name: "Mule",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 1,
		name: "Jumper",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 2,
		name: "Explorer",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 3,
		name: "Prospector",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 4,
		name: "Pioneer",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 5,
		name: "Space Digger",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 6,
		name: "Drone",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 7,
		name: "Pathfinder",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 8,
		name: "Vanguard",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 9,
		name: "Handshaker",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 10,
		name: "Senator",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 11,
		name: "Sunriser",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 12,
		name: "Auditor",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 13,
		name: "Comptroller",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 14,
		name: "Enforcer",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 15,
		name: "Chancellor",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 16,
		name: "Petrack",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 17,
		name: "Nomad",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 18,
		name: "Netrunner",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 19,
		name: "Highrider",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 20,
		name: "Apogee",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 21,
		name: "Journey to the West",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 22,
		name: "Earthly Demons",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 23,
		name: "Heavenly Spirits",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 24,
		name: "Three Kingdoms",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 25,
		name: "Fren",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 26,
		name: "Monocle",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 27,
		name: "Curve",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 28,
		name: "GHST",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 29,
		name: "Pickle",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 30,
		name: "Slice",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 31,
		name: "Sandwich",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 32,
		name: "The Mason Jar",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 33,
		name: "Anakuma",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 34,
		name: "Mellivora",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 35,
		name: "Leucurus",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 36,
		name: "Capensis",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 37,
		name: "Croissant",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 38,
		name: "Friendmaker",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 39,
		name: "Space Crab",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 40,
		name: "Liberator",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 41,
		name: "Arbitrator",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 42,
		name: "Pinakion",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 43,
		name: "Justitia",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 44,
		name: "Truthstar",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 45,
		name: "Konpeito",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 46,
		name: "Ramune",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 47,
		name: "Anpan",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 48,
		name: "Higashi",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 49,
		name: "Consul",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 50,
		name: "Gemini",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 51,
		name: "Gorgo",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 52,
		name: "Detos",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 53,
		name: "Foresight",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 54,
		name: "Annuarre",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 55,
		name: "Mot",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 56,
		name: "Ape-X",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 57,
		name: "Dogg’O",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 58,
		name: "G-raff",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 59,
		name: "Mastodon",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 60,
		name: "Le France",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 61,
		name: "The Alata",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 62,
		name: "The Trifida",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 63,
		name: "The Rotunda",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 64,
		name: "Dragonfly",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 65,
		name: "Spiritus",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 66,
		name: "Time Attack",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 67,
		name: "Strider",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 68,
		name: "Monolith",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 69,
		name: "Sound Wave",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
];

export default spaceships;
