const spaceships = [
	{
		id: 1000,
		href: "Mule",
		supply: 1,
		name: "Mule",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 1,
		name: "Jumper",
		href: "Jumper",
		supply: 1000,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 2,
		name: "Explorer",
		href: "Explorer",
		supply: 1000,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 3,
		name: "Prospector",
		href: "Prospector",
		supply: 100,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 4,
		name: "Pioneer",
		href: "Pioneer",
		supply: 100,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 5,
		href: "Space-Digger",
		name: "Space Digger",
		supply: 10,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 6,
		href: "Drone",
		name: "Drone",
		supply: 1000,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 7,
		href: "Pathfinder",
		name: "Pathfinder",
		supply: 1000,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 8,
		href: "Vanguard",
		name: "Vanguard",
		supply: 100,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 9,
		href: "Handshaker",
		name: "Handshaker",
		supply: 100,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 10,
		href: "Senator",
		name: "Senator",
		supply: 10,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 11,
		href: "Sunriser",
		name: "Sunriser",
		supply: 3,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 12,
		href: "Auditor",
		name: "Auditor",
		supply: 300,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 13,
		href: "Comptroller",
		name: "Comptroller",
		supply: 80,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 14,
		href: "Enforcer",
		name: "Enforcer",
		supply: 15,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 15,
		href: "Chancellor",
		name: "Chancellor",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 16,
		href: "Petrack",
		name: "Petrack",
		supply: 100,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 17,
		href: "Nomad",
		name: "Nomad",
		supply: 50,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 18,
		href: "Netrunner",
		name: "Netrunner",
		supply: 10,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 19,
		href: "Highrider",
		name: "Highrider",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 20,
		href: "Apogee",
		name: "Apogee",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 21,
		href: "Journey-to-the-West",
		name: "Journey to the West",
		supply: 777,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 22,
		href: "Earthly-Demons",
		name: "Earthly Demons",
		supply: 72,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 23,
		href: "Heavenly-Spirits",
		name: "Heavenly Spirits",
		supply: 36,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 24,
		href: "Three-Kingdoms",
		name: "Three Kingdoms",
		supply: 3,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 25,
		href: "Fren",
		name: "Fren",
		supply: 200,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 26,
		href: "Monocle",
		name: "Monocle",
		supply: 200,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 27,
		href: "Curve",
		name: "Curve",
		supply: 10,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 28,
		href: "GHST",
		name: "GHST",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 29,
		href: "Pickle",
		name: "Pickle",
		supply: 50,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 30,
		href: "Slice",
		name: "Slice",
		supply: 50,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 31,
		href: "Sandwich",
		name: "Sandwich",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 32,
		href: "The-Mason-Jar",
		name: "The Mason Jar",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 33,
		href: "Anakuma",
		name: "Anakuma",
		supply: 100,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 34,
		href: "Mellivora",
		name: "Mellivora",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 35,
		href: "Leucurus",
		name: "Leucurus",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 36,
		name: "Capensis",
		href: "Capensis",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 37,
		href: "Croissant",
		name: "Croissant",
		supply: 50,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 38,
		href: "Friendmaker",
		name: "Friendmaker",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 39,
		href: "Space-Crab",
		name: "Space Crab",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 40,
		href: "Liberator",
		name: "Liberator",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 41,
		href: "Arbitrator",
		name: "Arbitrator",
		supply: 25,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 42,
		href: "Pinakion",
		name: "Pinakion",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 43,
		href: "Justitia",
		name: "Justitia",
		supply: 5,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 44,
		href: "Truthstar",
		name: "Truthstar",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 45,
		href: "Konpeito",
		name: "Konpeito",
		supply: 300,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 46,
		href: "Ramune",
		name: "Ramune",
		supply: 30,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 47,
		href: "Anpan",
		name: "Anpan",
		supply: 3,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 48,
		href: "Higashi",
		name: "Higashi",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 49,
		href: "Consul",
		name: "Consul",
		supply: 3,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 50,
		href: "Gemini",
		name: "Gemini",
		supply: 10,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 51,
		href: "Gorgo",
		name: "Gorgo",
		supply: 3,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 52,
		href: "Detos",
		name: "Detos",
		supply: 50,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 53,
		href: "Foresight",
		name: "Foresight",
		supply: 24,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 54,
		href: "Annuarre",
		name: "Annuarre",
		supply: 4,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 55,
		href: "Mot",
		name: "Mot",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 56,
		href: "Ape-X",
		name: "Ape-X",
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 57,
		href: "Dogg'O",
		name: "Dogg'O",
		supply: 60,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 58,
		href: "G-raff",
		name: "G-raff",
		supply: 8,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 59,
		href: "Mastodon",
		name: "Mastodon",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 60,
		href: "Le-France",
		name: "Le France",
		supply: 10,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 61,
		href: "The-Alata",
		name: "The Alata",
		supply: 300,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 62,
		href: "The-Trifida",
		name: "The Trifida",
		supply: 50,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 63,
		href: "The-Rotunda",
		name: "The Rotunda",
		supply: 1,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 64,
		href: "Dragonfly",
		name: "Dragonfly",
		supply: 1000,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 65,
		href: "Spiritus",
		name: "Spiritus",
		supply: 100,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 66,
		href: "Time-Attack",
		name: "Time Attack",
		supply: 50,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 67,
		href: "Strider",
		name: "Strider",
		supply: 10,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 68,
		href: "Monolith",
		name: "Monolith",
		supply: 40,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
	{
		id: 69,
		href: "Sound-Wave",
		name: "Sound Wave",
		supply: 300,
		primaryColor: null,
		secondaryColor: null,
		currentOwner: null,
		status: null,
		primaryUse: null,
		length: null,
		width: null,
		height: null,
		topSpeed: null,
		crew: null,
		weapons: null,
	},
];

export default spaceships;
