const spaceships = [
  {
    id: 1000,
    href: "Mule",
    maxNumber: 1,
    name: "Mule",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 1,
    name: "Jumper",
    href: "Jumper",
    maxNumber: "1000",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 2,
    name: "Explorer",
    href: "Explorer",
    maxNumber: "1000",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 3,
    name: "Prospector",
    href: "Prospector",
    maxNumber: "100",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 4,
    name: "Pioneer",
    href: "Pioneer",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 5,
    href: "Space-Digger",
    name: "Space Digger",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 6,
    href: "Drone",
    name: "Drone",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 7,
    href: "Pathfinder",
    name: "Pathfinder",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 8,
    href: "Vanguard",
    name: "Vanguard",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 9,
    href: "Handshaker",
    name: "Handshaker",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 10,
    href: "Senator",
    name: "Senator",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 11,
    href: "Sunriser",
    name: "Sunriser",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 12,
    href: "Auditor",
    name: "Auditor",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 13,
    href: "Comptroller",
    name: "Comptroller",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 14,
    href: "Enforcer",
    name: "Enforcer",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 15,
    href: "Chancellor",
    name: "Chancellor",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 16,
    href: "Petrack",
    name: "Petrack",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 17,
    href: "Nomad",
    name: "Nomad",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 18,
    href: "Netrunner",
    name: "Netrunner",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 19,
    href: "Highrider",
    name: "Highrider",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 20,
    href: "Apogee",
    name: "Apogee",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 21,
    href: "Journey-to-the-West",
    name: "Journey to the West",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 22,
    href: "Earthly-Demons",
    name: "Earthly Demons",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 23,
    href: "Heavenly-Spirits",
    name: "Heavenly Spirits",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 24,
    href: "Three-Kingdoms",
    name: "Three Kingdoms",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 25,
    href: "Fren",
    name: "Fren",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 26,
    href: "Monocle",
    name: "Monocle",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 27,
    href: "Curve",
    name: "Curve",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 28,
    href: "GHST",
    name: "GHST",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 29,
    href: "Pickle",
    name: "Pickle",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 30,
    href: "Slice",
    name: "Slice",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 31,
    href: "Sandwich",
    name: "Sandwich",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 32,
    href: "The-Mason-Jar",
    name: "The Mason Jar",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 33,
    href: "Anakuma",
    name: "Anakuma",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 34,
    href: "Mellivora",
    name: "Mellivora",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 35,
    href: "Leucurus",
    name: "Leucurus",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 36,
    name: "Capensis",
    href: "Capensis",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 37,
    href: "Croissant",
    name: "Croissant",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 38,
    href: "Friendmaker",
    name: "Friendmaker",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 39,
    href: "Space-Crab",
    name: "Space Crab",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 40,
    href: "Liberator",
    name: "Liberator",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 41,
    href: "Arbitrator",
    name: "Arbitrator",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 42,
    href: "Pinakion",
    name: "Pinakion",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 43,
    href: "Justitia",
    name: "Justitia",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 44,
    href: "Truthstar",
    name: "Truthstar",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 45,
    href: "Konpeito",
    name: "Konpeito",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 46,
    href: "Ramune",
    name: "Ramune",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 47,
    href: "Anpan",
    name: "Anpan",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 48,
    href: "Higashi",
    name: "Higashi",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 49,
    href: "Consul",
    name: "Consul",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 50,
    href: "Gemini",
    name: "Gemini",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 51,
    href: "Gorgo",
    name: "Gorgo",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 52,
    href: "Detos",
    name: "Detos",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 53,
    href: "Foresight",
    name: "Foresight",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 54,
    href: "Annuarre",
    name: "Annuarre",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 55,
    href: "Mot",
    name: "Mot",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 56,
    href: "Ape-X",
    name: "Ape-X",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 57,
    href: "Dogg'O",
    name: "Dogg'O",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 58,
    href: "G-raff",
    name: "G-raff",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 59,
    href: "Mastodon",
    name: "Mastodon",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 60,
    href: "Le-France",
    name: "Le France",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 61,
    href: "The-Alata",
    name: "The Alata",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 62,
    href: "The-Trifida",
    name: "The Trifida",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 63,
    href: "The-Rotunda",
    name: "The Rotunda",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 64,
    href: "Dragonfly",
    name: "Dragonfly",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 65,
    href: "Spiritus",
    name: "Spiritus",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 66,
    href: "Time-Attack",
    name: "Time Attack",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 67,
    href: "Strider",
    name: "Strider",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 68,
    href: "Monolith",
    name: "Monolith",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
  {
    id: 69,
    href: "Sound-Wave",
    name: "Sound Wave",
    primaryColor: null,
    secondaryColor: null,
    currentOwner: null,
    status: null,
    primaryUse: null,
    length: null,
    width: null,
    height: null,
    topSpeed: null,
    crew: null,
    weapons: null,
  },
];

export default spaceships;
